interface ExportZipFileInput {
  themeName: string;
  themeCss: string;
  componentsCss: string;
  motionCss: string;
  tailwindConfig: string;
  tokensJson: string;
  figmaTokensJson: string;
  w3cDesignTokensJson: string;
  styleDictionaryJson: string;
  echartsThemeJson: string;
  iconsJson: string;
  appPreviewHtml: string;
  aiStyleGuide: string;
  aiPrompt: string;
  aiBuilderBrief: string;
  copyOncePrompt: string;
  tokenSavingsPrompt: string;
  iterationNotes: string;
  screenBuildPrompts: string;
  guardrailsPrompt: string;
  boilerplateNamingGuide: string;
  designRules: string;
  accessibilityNotes: string;
  baselineFrameworkGuide: string;
  templateStrategy: string;
  googleAiStudioPrompt: string;
  antigravityWorkflow: string;
  codexPrompt: string;
  chatGptPrompt: string;
  claudePrompt: string;
  geminiPrompt: string;
  cursorPrompt: string;
  lovablePrompt: string;
  boltPrompt: string;
  v0Prompt: string;
  replitPrompt: string;
  reactToggleCode: string;
  reactEChartsCode: string;
  goDbCode: string;
  stackReadmeCode: string;
}

function handoffFiles(input: ExportZipFileInput): Record<string, string> {
  return {
    "handoff/AI_BUILDER_BRIEF.md": input.aiBuilderBrief,
    "handoff/COPY_ONCE_PROMPT.md": input.copyOncePrompt,
    "handoff/TOKEN_SAVINGS_PROMPT.md": input.tokenSavingsPrompt,
    "handoff/ITERATION_NOTES.md": input.iterationNotes,
    "handoff/SCREEN_BUILD_PROMPTS.md": input.screenBuildPrompts,
    "handoff/DO_NOT_CHANGE_GUARDRAILS.md": input.guardrailsPrompt,
    "handoff/BOILERPLATE_NAMING_GUIDE.md": input.boilerplateNamingGuide,
    "handoff/DESIGN_RULES.md": input.designRules,
    "handoff/ACCESSIBILITY_NOTES.md": input.accessibilityNotes,
    "handoff/BASELINE_FRAMEWORK_GUIDE.md": input.baselineFrameworkGuide,
    "handoff/TEMPLATE_STRATEGY.md": input.templateStrategy,
  };
}

function toolPromptFiles(input: ExportZipFileInput): Record<string, string> {
  return {
    "handoff/GOOGLE_AI_STUDIO_PROMPT.md": input.googleAiStudioPrompt,
    "handoff/ANTIGRAVITY_WORKFLOW.md": input.antigravityWorkflow,
    "handoff/CODEX_PROMPT.md": input.codexPrompt,
    "handoff/CHATGPT_PROMPT.md": input.chatGptPrompt,
    "handoff/CLAUDE_PROMPT.md": input.claudePrompt,
    "handoff/GEMINI_PROMPT.md": input.geminiPrompt,
    "handoff/CURSOR_PROMPT.md": input.cursorPrompt,
    "handoff/LOVABLE_PROMPT.md": input.lovablePrompt,
    "handoff/BOLT_PROMPT.md": input.boltPrompt,
    "handoff/V0_PROMPT.md": input.v0Prompt,
    "handoff/REPLIT_PROMPT.md": input.replitPrompt,
  };
}

export function buildStackZipFiles(input: ExportZipFileInput): Record<string, string> {
  return {
    "styles/theme.css": input.themeCss,
    "styles/components.css": input.componentsCss,
    "config/tailwind.config.ts": input.tailwindConfig,
    "components/ThemeToggle.tsx": input.reactToggleCode,
    "components/EChartsWrapper.tsx": input.reactEChartsCode,
    "database/theme_store.go": input.goDbCode,
    ...handoffFiles(input),
    ...toolPromptFiles(input),
    "handoff/ai-prompt.txt": input.aiPrompt,
    "README.md": input.stackReadmeCode,
  };
}

export function buildAiHandoffZipFiles(input: ExportZipFileInput): Record<string, string> {
  return {
    ...handoffFiles(input),
    ...toolPromptFiles(input),
    "handoff/ai-prompt.txt": input.aiPrompt,
    "styles/theme.css": input.themeCss,
    "styles/components.css": input.componentsCss,
    "styles/motion.css": input.motionCss,
    "config/tailwind.config.ts": input.tailwindConfig,
    "tokens/style-tokens.json": input.tokensJson,
    "tokens/figma-tokens.json": input.figmaTokensJson,
    "tokens/w3c-design-tokens.json": input.w3cDesignTokensJson,
    "tokens/style-dictionary-tokens.json": input.styleDictionaryJson,
    "README.md": `# ${input.themeName} - AI Handoff Pack

This offline handoff pack was generated by App Style Studio.

## Recommended Workflow
1. Review \`handoff/AI_BUILDER_BRIEF.md\`.
2. Use \`handoff/COPY_ONCE_PROMPT.md\` when you need the shortest high-signal prompt for token-saving AI work.
3. Review \`handoff/BASELINE_FRAMEWORK_GUIDE.md\` if you are building from the user's Test Framework baseline.
4. Review \`handoff/TEMPLATE_STRATEGY.md\` to keep the gold baseline first and variants second.
5. Use \`handoff/GOOGLE_AI_STUDIO_PROMPT.md\` to generate or refine starter templates.
6. Use the relevant per-tool prompt for ChatGPT, Claude, Gemini, Cursor, Lovable, Bolt, v0, Replit, Antigravity, or Codex.
7. Keep \`handoff/DO_NOT_CHANGE_GUARDRAILS.md\`, \`handoff/BOILERPLATE_NAMING_GUIDE.md\`, \`handoff/DESIGN_RULES.md\`, and \`handoff/ACCESSIBILITY_NOTES.md\` attached so the AI tool does not drift from the design system, file structure, or accessibility requirements.

## Core Files
- \`styles/theme.css\`
- \`styles/components.css\`
- \`config/tailwind.config.ts\`
- \`tokens/style-tokens.json\`
- \`tokens/w3c-design-tokens.json\`
- \`tokens/style-dictionary-tokens.json\`
`,
  };
}

export function buildFullHandoffZipFiles(input: ExportZipFileInput): Record<string, string> {
  return {
    "README.md": `# ${input.themeName} - Full App Style Studio Handoff

This complete handoff pack includes every export needed for deeper implementation, template creation, and AI-assisted app building.

## Recommended Workflow
1. Start with \`handoff/COPY_ONCE_PROMPT.md\` when you want the shortest token-saving prompt.
2. Use \`handoff/AI_BUILDER_BRIEF.md\`, \`handoff/DESIGN_RULES.md\`, and \`handoff/ACCESSIBILITY_NOTES.md\` for complete build guidance.
3. Use \`handoff/BASELINE_FRAMEWORK_GUIDE.md\` if building from \`C:\\Users\\Home\\Desktop\\Test Framework\`.
4. Use \`handoff/TEMPLATE_STRATEGY.md\` to keep the gold baseline first and variants second.
5. Pick the relevant file in \`tool-prompts/\` for your AI tool.
6. Apply \`styles/theme.css\`, \`styles/components.css\`, \`styles/motion.css\`, and \`config/tailwind.config.ts\` before building screens.

## Folder Map
- \`styles/\`: CSS variables, component classes, and motion rules.
- \`config/\`: Tailwind token mapping.
- \`tokens/\`: JSON exports for tools and future imports.
- \`handoff/\`: Core AI handoff documents and guardrails.
- \`tool-prompts/\`: Prompt presets for specific AI builders.
- \`components/\`: Example React helper components.
- \`database/\`: Example Wails/SQLite helper.
- \`previews/\`: Standalone HTML preview.

## Quality Bar
Do not redesign the theme. Build with exported tokens, preserve accessibility states, verify desktop/tablet/mobile layouts, and run the project build before handoff.
`,
    "styles/theme.css": input.themeCss,
    "styles/components.css": input.componentsCss,
    "styles/motion.css": input.motionCss,
    "config/tailwind.config.ts": input.tailwindConfig,
    "tokens/style-tokens.json": input.tokensJson,
    "tokens/figma-tokens.json": input.figmaTokensJson,
    "tokens/w3c-design-tokens.json": input.w3cDesignTokensJson,
    "tokens/style-dictionary-tokens.json": input.styleDictionaryJson,
    "tokens/echarts-theme.json": input.echartsThemeJson,
    "tokens/icons.json": input.iconsJson,
    "previews/app-preview.html": input.appPreviewHtml,
    ...handoffFiles(input),
    "handoff/AI_STYLE_GUIDE.md": input.aiStyleGuide,
    "handoff/ai-prompt.txt": input.aiPrompt,
    "tool-prompts/GOOGLE_AI_STUDIO_PROMPT.md": input.googleAiStudioPrompt,
    "tool-prompts/ANTIGRAVITY_WORKFLOW.md": input.antigravityWorkflow,
    "tool-prompts/CODEX_PROMPT.md": input.codexPrompt,
    "tool-prompts/CHATGPT_PROMPT.md": input.chatGptPrompt,
    "tool-prompts/CLAUDE_PROMPT.md": input.claudePrompt,
    "tool-prompts/GEMINI_PROMPT.md": input.geminiPrompt,
    "tool-prompts/CURSOR_PROMPT.md": input.cursorPrompt,
    "tool-prompts/LOVABLE_PROMPT.md": input.lovablePrompt,
    "tool-prompts/BOLT_PROMPT.md": input.boltPrompt,
    "tool-prompts/V0_PROMPT.md": input.v0Prompt,
    "tool-prompts/REPLIT_PROMPT.md": input.replitPrompt,
    "components/ThemeToggle.tsx": input.reactToggleCode,
    "components/EChartsWrapper.tsx": input.reactEChartsCode,
    "database/theme_store.go": input.goDbCode,
    "stack/README.md": input.stackReadmeCode,
  };
}
