// Design System Presets for Non-Coder Simplicity

import { ColorTokens, TypographyTokens, SpacingTokens, RadiusTokens, ShadowTokens, IconSettings, MotionTokens, ComponentStyles } from '../types';

export interface PresetTheme {
  name: string;
  app_type: string;
  style_mood: string;
  default_mode: string;
  density: string;
  border_style: string;
  component_style: string;
  colour_tokens: ColorTokens;
  typography_tokens: TypographyTokens;
  spacing_tokens: SpacingTokens;
  radius_tokens: RadiusTokens;
  shadow_tokens: ShadowTokens;
  icon_settings: IconSettings;
  motion_tokens: MotionTokens;
}

export const SpacingPresets: Record<string, SpacingTokens> = {
  "Compact (Dense & Professional)": {
    xs: "2px",
    sm: "4px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    xxl: "24px",
    xxxl: "32px",
    page_padding: "12px",
    section_gap: "16px",
    card_padding: "12px",
    form_gap: "8px",
    table_cell_padding: "6px",
    sidebar_width: "200px",
    topbar_height: "48px",
    modal_width: "420px",
    dashboard_grid_gap: "12px",
    preset_name: "Compact (Dense & Professional)",
  },
  "Comfortable (Standard UI)": {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    xxl: "48px",
    xxxl: "64px",
    page_padding: "24px",
    section_gap: "32px",
    card_padding: "20px",
    form_gap: "16px",
    table_cell_padding: "12px",
    sidebar_width: "260px",
    topbar_height: "64px",
    modal_width: "540px",
    dashboard_grid_gap: "20px",
    preset_name: "Comfortable (Standard UI)",
  },
  "Spacious (Clean & Relaxed)": {
    xs: "6px",
    sm: "12px",
    md: "24px",
    lg: "36px",
    xl: "48px",
    xxl: "72px",
    xxxl: "96px",
    page_padding: "36px",
    section_gap: "48px",
    card_padding: "28px",
    form_gap: "24px",
    table_cell_padding: "18px",
    sidebar_width: "280px",
    topbar_height: "72px",
    modal_width: "620px",
    dashboard_grid_gap: "28px",
    preset_name: "Spacious (Clean & Relaxed)",
  }
};

export const TypographyPresets: Record<string, TypographyTokens> = {
  "Professional Sans": {
    heading_font: "Inter",
    body_font: "Inter",
    mono_font: "JetBrains Mono",
    base_font_size: 16,
    scale_ratio: 1.25,
    heading_sizes: { h1: "2.25rem", h2: "1.875rem", h3: "1.5rem", h4: "1.25rem", h5: "1.125rem", h6: "1rem" },
    body_text_size: "1rem",
    small_text_size: "0.875rem",
    muted_text_size: "0.875rem",
    table_text_size: "0.875rem",
    button_text_size: "0.875rem",
    label_text_size: "0.875rem",
    font_weights: { normal: "400", medium: "500", bold: "700" },
    line_heights: { normal: "1.5", tight: "1.25", loose: "1.75" },
    letter_spacings: { normal: "0", wide: "0.025em" },
    preset_name: "Professional Sans",
  },
  "Modern Dashboard": {
    heading_font: "Manrope",
    body_font: "Inter",
    mono_font: "SFMono-Regular",
    base_font_size: 16,
    scale_ratio: 1.33,
    heading_sizes: { h1: "2.35rem", h2: "1.77rem", h3: "1.33rem", h4: "1rem", h5: "0.875rem", h6: "0.75rem" },
    body_text_size: "1rem",
    small_text_size: "0.875rem",
    muted_text_size: "0.875rem",
    table_text_size: "0.875rem",
    button_text_size: "0.875rem",
    label_text_size: "0.875rem",
    font_weights: { normal: "400", medium: "500", bold: "700" },
    line_heights: { normal: "1.6", tight: "1.3", loose: "1.8" },
    letter_spacings: { normal: "-0.01em", wide: "0.05em" },
    preset_name: "Modern Dashboard",
  },
  "Military/Technical": {
    heading_font: "Space Grotesk",
    body_font: "Fira Code",
    mono_font: "JetBrains Mono",
    base_font_size: 15,
    scale_ratio: 1.2,
    heading_sizes: { h1: "2.07rem", h2: "1.73rem", h3: "1.44rem", h4: "1.2rem", h5: "1rem", h6: "0.875rem" },
    body_text_size: "0.938rem",
    small_text_size: "0.813rem",
    muted_text_size: "0.813rem",
    table_text_size: "0.813rem",
    button_text_size: "0.875rem",
    label_text_size: "0.813rem",
    font_weights: { normal: "400", medium: "500", bold: "700" },
    line_heights: { normal: "1.4", tight: "1.15", loose: "1.6" },
    letter_spacings: { normal: "0.02em", wide: "0.08em" },
    preset_name: "Military/Technical",
  },
  "Soft & Friendly": {
    heading_font: "Outfit",
    body_font: "Plus Jakarta Sans",
    mono_font: "Space Mono",
    base_font_size: 16,
    scale_ratio: 1.25,
    heading_sizes: { h1: "2.25rem", h2: "1.875rem", h3: "1.5rem", h4: "1.25rem", h5: "1.125rem", h6: "1rem" },
    body_text_size: "1rem",
    small_text_size: "0.875rem",
    muted_text_size: "0.875rem",
    table_text_size: "0.875rem",
    button_text_size: "0.875rem",
    label_text_size: "0.875rem",
    font_weights: { normal: "400", medium: "600", bold: "800" },
    line_heights: { normal: "1.5", tight: "1.2", loose: "1.75" },
    letter_spacings: { normal: "-0.02em", wide: "0.03em" },
    preset_name: "Soft & Friendly",
  }
};

export const RadiusPresets: Record<string, RadiusTokens> = {
  "Sharp (Tactical/Retro)": {
    none: "0px",
    sm: "0px",
    md: "0px",
    lg: "0px",
    xl: "0px",
    pill: "9999px",
  },
  "Subtle Rounded (Corporate)": {
    none: "0px",
    sm: "4px",
    md: "6px",
    lg: "8px",
    xl: "12px",
    pill: "9999px",
  },
  "Modern Rounded (Standard)": {
    none: "0px",
    sm: "6px",
    md: "10px",
    lg: "16px",
    xl: "22px",
    pill: "9999px",
  },
  "Pill Soft (Friendly)": {
    none: "0px",
    sm: "8px",
    md: "14px",
    lg: "24px",
    xl: "32px",
    pill: "9999px",
  }
};

export const ShadowPresets: Record<string, ShadowTokens> = {
  "Flat (No Depth)": {
    none: "none",
    sm: "none",
    md: "none",
    lg: "none",
    xl: "none",
    card: "none",
    modal: "none",
    dropdown: "none",
    button: "none",
    focus_ring: "0 0 0 2px rgba(124, 102, 220, 0.4)",
  },
  "Subtle (Sleek Professional)": {
    none: "none",
    sm: "0 1px 2px rgba(0,0,0,0.05)",
    md: "0 2px 4px rgba(0,0,0,0.05), 0 1px 2px rgba(0,0,0,0.05)",
    lg: "0 4px 6px rgba(0,0,0,0.05), 0 2px 4px rgba(0,0,0,0.05)",
    xl: "0 10px 15px rgba(0,0,0,0.05), 0 4px 6px rgba(0,0,0,0.05)",
    card: "0 4px 20px rgba(0,0,0,0.08)",
    modal: "0 10px 30px rgba(0,0,0,0.15)",
    dropdown: "0 4px 12px rgba(0,0,0,0.1)",
    button: "0 2px 6px rgba(0,0,0,0.08)",
    focus_ring: "0 0 0 3px rgba(124, 102, 220, 0.3)",
  },
  "High Contrast Depth (Sajid Style)": {
    none: "none",
    sm: "0 1px 2px rgba(0,0,0,0.1)",
    md: "0 4px 10px rgba(0,0,0,0.15)",
    lg: "0 10px 25px rgba(0,0,0,0.2)",
    xl: "0 20px 40px rgba(0,0,0,0.3)",
    card: "0 10px 30px rgba(0,0,0,0.35)",
    modal: "0 30px 60px rgba(0,0,0,0.5)",
    dropdown: "0 12px 24px rgba(0,0,0,0.4)",
    button: "0 4px 14px rgba(0,0,0,0.25)",
    focus_ring: "0 0 0 4px rgba(124, 102, 220, 0.5)",
  }
};

export const PresetThemes: PresetTheme[] = [
  {
    name: "Emerald Command",
    app_type: "Admin Dashboard",
    style_mood: "Modern",
    default_mode: "Dark",
    density: "Comfortable",
    border_style: "Subtle",
    component_style: "Rounded",
    colour_tokens: {
      base_hue: 145,
      chroma: 0.04,
      warm_cool: 0,
      neutral_vivid: 0.05,
      lightness: 0.5,
      shadow_colorize: true,
      shadow_intensity: 0.25,
      highlight_opacity: 0.08,
      glass_enabled: false,
      glass_blur: 12.0,
      glass_opacity: 0.25,
      harmony: "complementary",
      overrides: {},
    },
    typography_tokens: TypographyPresets["Modern Dashboard"],
    spacing_tokens: SpacingPresets["Comfortable (Standard UI)"],
    radius_tokens: RadiusPresets["Modern Rounded (Standard)"],
    shadow_tokens: ShadowPresets["High Contrast Depth (Sajid Style)"],
    icon_settings: {
      library: "Lucide",
      default_size: "20px",
      sidebar_size: "22px",
      button_size: "18px",
      table_action_size: "16px",
      stroke_width: "2px",
      colour_behaviour: "inherit text",
      mappings: {
        Dashboard: "LayoutDashboard",
        Setup: "Settings",
        Users: "Users",
        Reports: "BarChart",
        Finance: "CreditCard",
        Calendar: "Calendar",
        Documents: "FileText",
        Search: "Search",
        Filter: "Filter",
        Export: "Download",
        Edit: "Edit",
        Delete: "Trash",
        Save: "Save",
        Warning: "AlertTriangle",
        Success: "CheckCircle",
        Info: "Info",
      }
    },
    motion_tokens: {
      enabled: true,
      global_speed: "normal",
      button_hover: "scale-up",
      button_press: "scale-down",
      card_hover: "lift",
      modal_animation: "fade-in-scale",
      sidebar_animation: "slide-in-left",
      page_transition: "fade-in",
      alert_animation: "slide-in-right",
      loading_animation: "spin",
      duration_fast: "150ms",
      duration_normal: "300ms",
      duration_slow: "500ms",
      ease_standard: "cubic-bezier(0.4, 0, 0.2, 1)",
      ease_emphasised: "cubic-bezier(0.2, 0.8, 0.2, 1)",
      ease_bounce: "cubic-bezier(0.34, 1.56, 0.64, 1)",
    }
  },
  {
    name: "Tactical Console",
    app_type: "Tactical Console",
    style_mood: "Tactical",
    default_mode: "Dark",
    density: "Compact",
    border_style: "Strong",
    component_style: "Sharp",
    colour_tokens: {
      base_hue: 200,
      chroma: 0.02,
      warm_cool: 0,
      neutral_vivid: 0.02,
      lightness: 0.5,
      shadow_colorize: false,
      shadow_intensity: 0,
      highlight_opacity: 0,
      glass_enabled: false,
      glass_blur: 0,
      glass_opacity: 0,
      harmony: "complementary",
      overrides: {},
    },
    typography_tokens: TypographyPresets["Military/Technical"],
    spacing_tokens: SpacingPresets["Compact (Dense & Professional)"],
    radius_tokens: RadiusPresets["Sharp (Tactical/Retro)"],
    shadow_tokens: ShadowPresets["Flat (No Depth)"],
    icon_settings: {
      library: "Lucide",
      default_size: "18px",
      sidebar_size: "20px",
      button_size: "16px",
      table_action_size: "14px",
      stroke_width: "1.5px",
      colour_behaviour: "primary",
      mappings: {
        Dashboard: "Terminal",
        Setup: "Sliders",
        Users: "Cpu",
        Reports: "Activity",
        Finance: "Shield",
        Calendar: "Clock",
        Documents: "FileCode",
        Search: "Search",
        Filter: "Filter",
        Export: "Download",
        Edit: "Wrench",
        Delete: "XOctagon",
        Save: "Save",
        Warning: "AlertOctagon",
        Success: "CheckSquare",
        Info: "HelpCircle",
      }
    },
    motion_tokens: {
      enabled: false,
      global_speed: "fast",
      button_hover: "none",
      button_press: "none",
      card_hover: "none",
      modal_animation: "none",
      sidebar_animation: "none",
      page_transition: "none",
      alert_animation: "none",
      loading_animation: "spin",
      duration_fast: "50ms",
      duration_normal: "100ms",
      duration_slow: "200ms",
      ease_standard: "linear",
      ease_emphasised: "linear",
      ease_bounce: "linear",
    }
  },
  {
    name: "Corporate Pro",
    app_type: "Admin Dashboard",
    style_mood: "Corporate",
    default_mode: "Both",
    density: "Comfortable",
    border_style: "Subtle",
    component_style: "Rounded",
    colour_tokens: {
      base_hue: 220,
      chroma: 0.03,
      warm_cool: 0,
      neutral_vivid: 0.04,
      lightness: 0.5,
      shadow_colorize: true,
      shadow_intensity: 0.2,
      highlight_opacity: 0.05,
      glass_enabled: false,
      glass_blur: 8.0,
      glass_opacity: 0.2,
      harmony: "complementary",
      overrides: {},
    },
    typography_tokens: TypographyPresets["Professional Sans"],
    spacing_tokens: SpacingPresets["Comfortable (Standard UI)"],
    radius_tokens: RadiusPresets["Subtle Rounded (Corporate)"],
    shadow_tokens: ShadowPresets["Subtle (Sleek Professional)"],
    icon_settings: {
      library: "Lucide",
      default_size: "20px",
      sidebar_size: "22px",
      button_size: "18px",
      table_action_size: "16px",
      stroke_width: "2px",
      colour_behaviour: "inherit text",
      mappings: {
        Dashboard: "LayoutDashboard",
        Setup: "Settings",
        Users: "Users",
        Reports: "BarChart",
        Finance: "CreditCard",
        Calendar: "Calendar",
        Documents: "FileText",
        Search: "Search",
        Filter: "Filter",
        Export: "Download",
        Edit: "Edit",
        Delete: "Trash",
        Save: "Save",
        Warning: "AlertTriangle",
        Success: "CheckCircle",
        Info: "Info",
      }
    },
    motion_tokens: {
      enabled: true,
      global_speed: "normal",
      button_hover: "none",
      button_press: "scale-down",
      card_hover: "lift",
      modal_animation: "fade-in",
      sidebar_animation: "slide-in-left",
      page_transition: "fade-in",
      alert_animation: "slide-in-right",
      loading_animation: "spin",
      duration_fast: "200ms",
      duration_normal: "350ms",
      duration_slow: "600ms",
      ease_standard: "cubic-bezier(0.4, 0, 0.2, 1)",
      ease_emphasised: "cubic-bezier(0.2, 0.8, 0.2, 1)",
      ease_bounce: "cubic-bezier(0.2, 0.8, 0.2, 1)",
    }
  },
  {
    name: "Bubblegum Pop",
    app_type: "Client Portal",
    style_mood: "Soft",
    default_mode: "Light",
    density: "Spacious",
    border_style: "Glass",
    component_style: "Soft Card",
    colour_tokens: {
      base_hue: 330,
      chroma: 0.08,
      warm_cool: 0,
      neutral_vivid: 0.1,
      lightness: 0.5,
      shadow_colorize: true,
      shadow_intensity: 0.3,
      highlight_opacity: 0.12,
      glass_enabled: true,
      glass_blur: 16.0,
      glass_opacity: 0.35,
      harmony: "complementary",
      overrides: {},
    },
    typography_tokens: TypographyPresets["Soft & Friendly"],
    spacing_tokens: SpacingPresets["Spacious (Clean & Relaxed)"],
    radius_tokens: RadiusPresets["Pill Soft (Friendly)"],
    shadow_tokens: ShadowPresets["High Contrast Depth (Sajid Style)"],
    icon_settings: {
      library: "Lucide",
      default_size: "22px",
      sidebar_size: "24px",
      button_size: "20px",
      table_action_size: "18px",
      stroke_width: "2px",
      colour_behaviour: "inherit text",
      mappings: {
        Dashboard: "Smile",
        Setup: "Sparkles",
        Users: "Heart",
        Reports: "PieChart",
        Finance: "ShoppingBag",
        Calendar: "Star",
        Documents: "Bookmark",
        Search: "Search",
        Filter: "Filter",
        Export: "Heart",
        Edit: "PenTool",
        Delete: "Trash2",
        Save: "HeartHandshake",
        Warning: "AlertCircle",
        Success: "Check",
        Info: "MessageCircle",
      }
    },
    motion_tokens: {
      enabled: true,
      global_speed: "normal",
      button_hover: "scale-up",
      button_press: "scale-down",
      card_hover: "lift",
      modal_animation: "fade-in-scale",
      sidebar_animation: "slide-in-left",
      page_transition: "fade-in",
      alert_animation: "slide-in-right",
      loading_animation: "spin",
      duration_fast: "150ms",
      duration_normal: "300ms",
      duration_slow: "450ms",
      ease_standard: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      ease_emphasised: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      ease_bounce: "cubic-bezier(0.34, 1.56, 0.64, 1)",
    }
  }
];
