// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTheme(arg1) {
  return window['go']['main']['App']['DeleteTheme'](arg1);
}

export function DuplicateTheme(arg1) {
  return window['go']['main']['App']['DuplicateTheme'](arg1);
}

export function GetExportHistory() {
  return window['go']['main']['App']['GetExportHistory']();
}

export function GetTheme(arg1) {
  return window['go']['main']['App']['GetTheme'](arg1);
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function LogExport(arg1, arg2) {
  return window['go']['main']['App']['LogExport'](arg1, arg2);
}

export function SaveExportFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2);
}

export function SaveExportZip(arg1, arg2) {
  return window['go']['main']['App']['SaveExportZip'](arg1, arg2);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}
