// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTheme(arg1:number):Promise<void>;

export function DuplicateTheme(arg1:number):Promise<number>;

export function GetExportHistory():Promise<Array<main.ExportLog>>;

export function GetTheme(arg1:number):Promise<main.ThemeDetail>;

export function ListThemes():Promise<Array<main.Theme>>;

export function LogExport(arg1:number,arg2:string):Promise<void>;

export function SaveExportFile(arg1:string,arg2:string):Promise<string>;

export function SaveExportZip(arg1:string,arg2:Record<string, string>):Promise<string>;

export function SaveTheme(arg1:main.ThemeDetail):Promise<number>;
